#!/bin/bash
set -e

if ! command -v dialog > /dev/null; then
  echo "dialog is not installed, installing..." >&2
  sudo apt-get install dialog -y
fi
#Install nala if not installed for better terminal output
if ! command -v nala > /dev/null; then
  echo "nala is not installed, installing" >&2
  sudo apt-get install nala -y
fi

SELECTED=($( dialog --backtitle "Press 'space' to toggle an option, use arrow keys to go up/down, press enter to continue" --scrollbar --separate-output --checklist "Select Desktop Environment(s)" $(expr $(tput lines) - 5) $(expr $(tput cols) - 5) 5 \
  "1" "GNOME (Ubuntu)" OFF \
  "2" "GNOME Flashback" OFF \
  "3" "GNOME" OFF \
  "4" "KDE (Ubuntu)" OFF \
  "5" "KDE (Full)" OFF \
  "6" "KDE (Standard)" OFF \
  "7" "XFCE (Ubuntu)" OFF \
  "8" "XFCE" OFF \
  "9" "MATE (Ubuntu)" OFF \
  "10" "MATE" OFF \
  "11" "LXQt (Ubuntu)" OFF \
  "12" "LXQt" OFF \
  "13" "Budgie (Ubuntu)" OFF \
  "14" "Budgie" OFF \
  "15" "Unity" OFF \
  "16" "Cinnamon" OFF \
  "17" "UKUI" OFF \
  "18" "LXDE" OFF \
  "19" "i3" OFF \
  "20" "Sway" OFF \
  "21" "AwesomeWM" OFF \
  "22" "bspwm" OFF \
  "23" "DWM" OFF \
  "24" "Openbox" OFF \
  "25" "Enlightenment" OFF \
  3>&1 1>&2 2>&3))

for i in "${SELECTED[@]}"; do
  case $i in
    1)
      desktop+=("ubuntu-desktop")
      login_manager="gdm3"
      ;;
    2)
      desktop+=("gnome-session-flashback")
      login_manager="gdm3"
      ;;
    3)
      desktop+=("vanilla-gnome-desktop")
      login_manager="gdm3"
      ;;
    4)
      desktop+=("kubuntu-desktop")
      login_manager="sddm"
      ;;      
    5)
      desktop+=("kde-full")
      login_manager="sddm"
      ;;
    6)
      desktop+=("kde-standard")
      login_manager="sddm"
      ;;
    7)
      desktop+=("xubuntu-desktop")
      login_manager="lightdm"
      ;;
    8)
      desktop+=("xfce4" "xfce4-goodies")
      login_manager="lightdm"
      ;;
    9)
      desktop+=("ubuntu-mate-desktop")
      login_manager="lightdm"
      snap_package_classic="ubuntu-mate-welcome"
      ;;
    10)
      desktop+=("mate-desktop")
      login_manager="lightdm"
      ;;
    11)
      desktop+=("lubuntu-desktop")
      login_manager="sddm"
      ;;
    12)
      desktop+=("lxqt")
      login_manager="sddm"
      ;;
    13)
      desktop+=("ubuntu-budgie-desktop")
      login_manager="budgie-lightdm-theme-base"
      extra_packages="budgie-extras-common budgie-extras-daemon"
      ;;
    14)
      desktop+=("budgie-desktop")
      login_manager="budgie-lightdm-theme-base"
      extra_packages="budgie-extras-common budgie-extras-daemon"
      ;; 
    15)
      desktop+=("ubuntu-unity-desktop")
      login_manager="lightdm"
      extra_packages="dbus-x11 yaru-theme-unity yaru-theme-icon yaru-theme-gtk yaru-theme-sound unity-tweak-tool unity-lens-music unity-lens-photos unity-lens-video"
      ;;
    16)
      desktop+=("cinnamon")
      login_manager="lightdm"
      ;;
    17)
      desktop+=("ukui-desktop-environment")
      login_manager="ukui-greeter"
      extra_packages="obconf"
      ;;
    18)
      desktop+=("lxde")
      login_manager="lxdm"
      ;;
    19)
      desktop+=("i3")
      login_manager="lightdm"
      ;; 
    20)
      desktop+=("sway")
      login_manager="sddm"
      ;; 
    21)
      desktop+=("awesome")
      login_manager="lightdm"
      ;;
    22)
      desktop+=("bspwm")
      login_manager="lightdm"
      ;;
    23)
      desktop+=("dwm")
      login_manager="lightdm"
      ;;
    24)
      desktop+=("openbox")
      login_manager="lightdm"
      extra_packages="obconf"
      ;;
    25)
      desktop+=("enlightenment")
      login_manager="lightdm"
      ;;
  esac
done

clear

echo "Updating package cache..."
sudo nala update

echo "Checking for package existence..."
for i in "${desktop[@]}"; do
  if [[ $(apt-cache search --names-only "^$i\$") ]]; then
    echo "$i exists..."
  else
    echo "$i does not exist, exiting..." >&2
    exit 1
  fi
done

if [[ $(apt-cache search --names-only "^$login_manager\$") ]]; then
  echo "$i exists..."
else
  echo "$i does not exist, exiting..." >&2
  exit 1
fi
echo "Installing desktop and login manager..."
sudo nala install -y ${desktop[@]} "${login_manager}" ${extra_packages}
if [[ -n $remove_packages ]]; then
    echo "Removing unnecessary packages"
    sudo nala remove -y ${remove_packages}
    sudo nala autoremove -y
fi
echo "Set login manager to $login_manager"
sudo dpkg-reconfigure "${login_manager}"
echo "Done!"
clear
echo "Your desktop is now installed and ready for you to use. Go ahead and reboot your system to start using it!"
done
